; 设置配置文件.ini
; 配置集 1: 速率53.125Gbaud；波长1310；两路合一路码长131070
[53.125_1310_131070]
commands = 
    :MEASure:EYE:APOWer:UNITs DBM
    :CHANnel1A:DISPlay ON
    :CHANnel1A:SIGNal:TYPE PAM4
    :CHANnel1A:FILTer ON
    :CHANnel1A:FSELect:RATe 53125000000
    :CHANnel1A:SIRC:FBANdwidth 2.660000E+010
    :CHANnel1A:WAVelength:VALue 1.310000E-006
    :FUNCtion1:FOPerator NONE
    :FUNCtion1:FOPerator FFEQualizer
    :FUNCtion1:OPERand1 1A
    :FUNCtion1:DISPlay ON
    :SPRocess1:FFEQualizer:TAPS:AUTo ON
    :SPRocess1:FFEQualizer:TAPS:COUNt 13
    :SPRocess1:FFEQualizer:NPRecursors 0
    :MEASure:EYE:PAM:UNDershoot:SOURce FUNCtion1
    :MEASure:EYE:PAM:UNDershoot
    :MEASure:EYE:PAM:OVERshoot:SOURce FUNCtion1
    :MEASure:EYE:PAM:OVERshoot
    :MEASure:EYE:PAM:LINearity:DEFinition EYE
    :MEASure:EYE:PAM:LINearity:SOURce FUNCtion1
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LINearity:DEFinition RLMA120
    :MEASure:EYE:PAM:LINearity:SOURce FUNCtion1
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LINearity:DEFinition RLMC94
    :MEASure:EYE:PAM:LINearity:SOURce FUNCtion1
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LEVel:LEVel LEVel3
    :MEASure:EYE:PAM:LEVel:SOURce FUNCtion1
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel2
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel1
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel0
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:OOMA:SOURce FUNCtion1
    :MEASure:EYE:OOMA
    :MEASure:EYE:NMARgin:SOURce FUNCtion1
    :MEASure:EYE:NMARgin
    :MEASure:EYE:OER:SOURce FUNCtion1
    :MEASure:EYE:OER
    :MEASure:EYE:TDEQ:SOURce FUNCtion1
    :MEASure:EYE:TDEQ
    :MEASure:EYE:PAM:TPEXcursion:SOURce FUNCtion1
    :MEASure:EYE:PAM:TPEXcursion
    :MEASure:EYE:PAM:UNDershoot:SOURce CHANnel1A
    :MEASure:EYE:PAM:UNDershoot
    :MEASure:EYE:PAM:OVERshoot:SOURce CHANnel1A
    :MEASure:EYE:PAM:OVERshoot
    :MEASure:EYE:PAM:LINearity:DEFinition EYE
    :MEASure:EYE:PAM:LINearity:SOURce CHANnel1A
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LINearity:DEFinition RLMA120
    :MEASure:EYE:PAM:LINearity:SOURce CHANnel1A
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LINearity:DEFinition RLMC94
    :MEASure:EYE:PAM:LINearity:SOURce CHANnel1A
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LEVel:LEVel LEVel3
    :MEASure:EYE:PAM:LEVel:SOURce CHANnel1A
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel2
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel1
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel0
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:OOMA:SOURce CHANnel1A
    :MEASure:EYE:OOMA
    :MEASure:EYE:NMARgin:SOURce CHANnel1A
    :MEASure:EYE:NMARgin
    :MEASure:EYE:OER:SOURce CHANnel1A
    :MEASure:EYE:OER
    :MEASure:EYE:TDEQ:SOURce CHANnel1A
    :MEASure:EYE:TDEQ
    :MEASure:EYE:PAM:TPEXcursion:SOURce CHANnel1A
    :MEASure:EYE:PAM:TPEXcursion
    :MEASure:EYE:BITRate:SOURce CHANnel1A
    :MEASure:EYE:BITRate
    :MEASure:EYE:APOWer:SOURce CHANnel1A
    :MEASure:EYE:APOWer
    :TIMebase:SRATe 5.312500E+010
    :TRIGger:PLENgth 131070
    :MEASure:TDEQ:PRESets "IEEE 802.3cd"
    :SPRocess1:TEQualizer:PRESets "IEEE 802.3cd"

; 配置集 2: 速率53.125Gbaud；波长1310；码长65535
[53.125_1310_65535]
commands = 
    :MEASure:EYE:APOWer:UNITs DBM
    :CHANnel1A:DISPlay ON
    :CHANnel1A:SIGNal:TYPE PAM4
    :CHANnel1A:FILTer ON
    :CHANnel1A:FSELect:RATe 53125000000
    :CHANnel1A:SIRC:FBANdwidth 2.660000E+010
    :CHANnel1A:WAVelength:VALue 1.310000E-006
    :FUNCtion1:FOPerator NONE
    :FUNCtion1:FOPerator FFEQualizer
    :FUNCtion1:OPERand1 1A
    :FUNCtion1:DISPlay ON
    :SPRocess1:FFEQualizer:TAPS:AUTo ON
    :SPRocess1:FFEQualizer:TAPS:COUNt 13
    :SPRocess1:FFEQualizer:NPRecursors 0
    :MEASure:EYE:PAM:UNDershoot:SOURce FUNCtion1
    :MEASure:EYE:PAM:UNDershoot
    :MEASure:EYE:PAM:OVERshoot:SOURce FUNCtion1
    :MEASure:EYE:PAM:OVERshoot
    :MEASure:EYE:PAM:LINearity:DEFinition EYE
    :MEASure:EYE:PAM:LINearity:SOURce FUNCtion1
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LINearity:DEFinition RLMA120
    :MEASure:EYE:PAM:LINearity:SOURce FUNCtion1
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LINearity:DEFinition RLMC94
    :MEASure:EYE:PAM:LINearity:SOURce FUNCtion1
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LEVel:LEVel LEVel3
    :MEASure:EYE:PAM:LEVel:SOURce FUNCtion1
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel2
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel1
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel0
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:OOMA:SOURce FUNCtion1
    :MEASure:EYE:OOMA
    :MEASure:EYE:NMARgin:SOURce FUNCtion1
    :MEASure:EYE:NMARgin
    :MEASure:EYE:OER:SOURce FUNCtion1
    :MEASure:EYE:OER
    :MEASure:EYE:TDEQ:SOURce FUNCtion1
    :MEASure:EYE:TDEQ
    :MEASure:EYE:PAM:TPEXcursion:SOURce FUNCtion1
    :MEASure:EYE:PAM:TPEXcursion
    :MEASure:EYE:PAM:UNDershoot:SOURce CHANnel1A
    :MEASure:EYE:PAM:UNDershoot
    :MEASure:EYE:PAM:OVERshoot:SOURce CHANnel1A
    :MEASure:EYE:PAM:OVERshoot
    :MEASure:EYE:PAM:LINearity:DEFinition EYE
    :MEASure:EYE:PAM:LINearity:SOURce CHANnel1A
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LINearity:DEFinition RLMA120
    :MEASure:EYE:PAM:LINearity:SOURce CHANnel1A
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LINearity:DEFinition RLMC94
    :MEASure:EYE:PAM:LINearity:SOURce CHANnel1A
    :MEASure:EYE:PAM:LINearity
    :MEASure:EYE:PAM:LEVel:LEVel LEVel3
    :MEASure:EYE:PAM:LEVel:SOURce CHANnel1A
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel2
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel1
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:PAM:LEVel:LEVel LEVel0
    :MEASure:EYE:PAM:LEVel
    :MEASure:EYE:OOMA:SOURce CHANnel1A
    :MEASure:EYE:OOMA
    :MEASure:EYE:NMARgin:SOURce CHANnel1A
    :MEASure:EYE:NMARgin
    :MEASure:EYE:OER:SOURce CHANnel1A
    :MEASure:EYE:OER
    :MEASure:EYE:TDEQ:SOURce CHANnel1A
    :MEASure:EYE:TDEQ
    :MEASure:EYE:PAM:TPEXcursion:SOURce CHANnel1A
    :MEASure:EYE:PAM:TPEXcursion
    :MEASure:EYE:BITRate:SOURce CHANnel1A
    :MEASure:EYE:BITRate
    :MEASure:EYE:APOWer:SOURce CHANnel1A
    :MEASure:EYE:APOWer
    :TIMebase:SRATe 5.312500E+010
    :TRIGger:PLENgth 65535
    :MEASure:TDEQ:PRESets "IEEE 802.3cd"
    :SPRocess1:TEQualizer:PRESets "IEEE 802.3cd"

; 配置集 3: 速率49.7664Gbaud；波长1310；码长65534
[49.7664_1310_65534]
commands = 
    :MEASure:EYE:APOWer:UNITs DBM
    :CHANnel1A:FILTer ON
    :CHANnel1A:FSELect:RATe 49000000000
    :CHANnel1A:SIRC:FBANdwidth 3.730000E+010
    :CHANnel1A:WAVelength:VALue 1.310000E-006
    :FUNCtion1:FOPerator NONE
    :FUNCtion1:FOPerator FFEQualizer
    :FUNCtion1:OPERand1 1A
    :FUNCtion1:DISPlay ON
    :SPRocess1:FFEQualizer:TAPS:AUTo ON
    :SPRocess1:FFEQualizer:TAPS:COUNt 7
    :SPRocess1:FFEQualizer:NPRecursors 3
    :CHANnel1B:FILTer ON
    :CHANnel1B:FSELect:RATe 49000000000
    :CHANnel1B:SIRC:FBANdwidth 3.730000E+010
    :CHANnel1B:WAVelength:VALue 1.310000E-006
    :MEASure:EYE:JITTer:FORMat RMS
    :MEASure:EYE:JITTer:SOURce FUNCtion1
    :MEASure:EYE:JITTer
    :MEASure:EYE:JITTer:FORMat PP
    :MEASure:EYE:JITTer
    :MEASure:EYE:RISetime:SOURce FUNCtion1
    :MEASure:EYE:RISetime
    :MEASure:EYE:FALLtime:SOURce FUNCtion1
    :MEASure:EYE:FALLtime
    :MEASure:EYE:CROSsing:SOURce FUNCtion1
    :MEASure:EYE:CROSsing
    :MEASure:EYE:OLEVel:SOURce FUNCtion1
    :MEASure:EYE:OLEVel
    :MEASure:EYE:ZLEVel:SOURce FUNCtion1
    :MEASure:EYE:ZLEVel
    :MEASure:EYE:OMAXp:SOURce FUNCtion1
    :MEASure:EYE:OMAXp
    :MEASure:EYE:TDEC:SOURce FUNCtion1
    :MEASure:EYE:TDEC
    :MEASure:EYE:CEQ:SOURce FUNCtion1
    :MEASure:EYE:CEQ
    :MEASure:EYE:ERATio:SOURce FUNCtion1
    :MEASure:EYE:ERATio
    :MTESt1:SOURce FUNCtion1
    :MTESt1:LOAD:FNAMe "50G_ONU_new.mskx"
    :MTESt1:LOAD
    :MTESt1:MARGin:STATe ON
    :MTESt1:MARGin:METHod AUTO
    :MTESt1:MARGin:PERCent 0.000
    :MTESt1:MARGin:AUTo:METHod HRATio
    :MTESt1:MARGin:AUTo:HRATio 5E-05
    :MTESt1:MARGin:AUTo:HITs 0
    :MEASure:EYE:JITTer:FORMat RMS
    :MEASure:EYE:JITTer:SOURce CHANnel1A
    :MEASure:EYE:JITTer
    :MEASure:EYE:JITTer:FORMat PP
    :MEASure:EYE:JITTer
    :MEASure:EYE:RISetime:SOURce CHANnel1A
    :MEASure:EYE:RISetime
    :MEASure:EYE:FALLtime:SOURce CHANnel1A
    :MEASure:EYE:FALLtime
    :MEASure:EYE:CROSsing:SOURce CHANnel1A
    :MEASure:EYE:CROSsing
    :MEASure:EYE:OLEVel:SOURce CHANnel1A
    :MEASure:EYE:OLEVel
    :MEASure:EYE:ZLEVel:SOURce CHANnel1A
    :MEASure:EYE:ZLEVel
    :MEASure:EYE:OMAXp:SOURce CHANnel1A
    :MEASure:EYE:OMAXp
    :MEASure:EYE:TDEC:SOURce CHANnel1A
    :MEASure:EYE:TDEC
    :MEASure:EYE:CEQ:SOURce CHANnel1A
    :MEASure:EYE:CEQ
    :MEASure:EYE:ERATio:SOURce CHANnel1A
    :MEASure:EYE:ERATio
    :MEASure:EYE:BITRate:SOURce CHANnel1A
    :MEASure:EYE:BITRate
    :MEASure:EYE:APOWer:SOURce CHANnel1A
    :MEASure:EYE:APOWer
    :MTESt2:SOURce CHANnel1A
    :MTESt2:LOAD:FNAMe "50G_ONU_new.mskx"
    :MTESt2:LOAD
    :MTESt2:MARGin:STATe ON
    :MTESt2:MARGin:METHod AUTO
    :MTESt2:MARGin:PERCent 0.000
    :MTESt2:MARGin:AUTo:METHod HRATio
    :MTESt2:MARGin:AUTo:HRATio 5E-05
    :MTESt2:MARGin:AUTo:HITs 0
    :TIMebase:SRATe 4.976640E+010
    :TRIGger:PLENgth 65534
    :MEASure:TDEQ:PRESets "IEEE 802.3cd"
